;;(load "config/builtins/dired")
;;(load "config/builtins/flyspell-mode")
;;(load "config/builtins/diff-mode")
(load "config/builtins/text-mode")
(load "config/builtins/cc-mode")
(load "config/builtins/emacs-lisp-mode")
(load "config/builtins/go-mode")
;;(load "config/builtins/semantic")
